apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kvm-csi-pvc-01
  namespace: csi-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: kvm-csi